### ISSUE TITLE
5minfork.com is unavailable

### ISSUE THREAD

**Issue by anissen** [remy/5minutefork#34]
[5minfork.com](http://5minfork.com) appears to [be down](http://www.downforeveryoneorjustme.com/5minfork.com) and have been that way for a while :cry:

**Comment by remy** [comment]
It has, and the server got blown away during a clean up. It will be back,
but I've got client work I have to complete, but hold tight!

**Comment by anissen** [comment]
Sounds good, thanks for the heads-up! :+1:

**Comment by kelvah** [comment]
we miss 5minfork.com :(

**Comment by TimPietrusky** [comment]
+1

**Comment by davidsalazar** [comment]
WTF.....you bastard.

**Comment by inlikealion** [comment]
Ah, I miss it too @remy ! Work comes first of course, but know that this tool is certainly appreciated by the github community.

**Comment by anissen** [comment]
Rejoice! **5minfork.com** is back! 🎉
